<a href="https://colab.research.google.com/github/Siraj-Ali8804/Scientific-Computing-/blob/main/Numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **What is Numpy?**
NumPy (Numerical Python) is a fundamental Python library for scientific computing, providing powerful N-dimensional array objects (ndarrays) and high-level mathematical functions for efficient manipulation of large datasets, making it crucial for data science, machine learning, and numerical analysis by offering speed and reduced memory usage compared to standard Python lists. Its core strength lies in its optimized, compiled-code operations on homogeneous, fixed-size arrays, enabling fast linear algebra, random simulations, and complex math

### **Numpy funtions**

In [ ]:
import numpy as np


In [ ]:
a= np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
#2D an3D array
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c= np.array([[[[1,2],[3,4],[5,6]]]])
print(c)

[[[[1 2]
   [3 4]
   [5 6]]]]


In [ ]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
np.array([1,2,4],dtype=complex)

array([1.+0.j, 2.+0.j, 4.+0.j])

In [ ]:
# np.arange , crate a range of as in list

np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#np.ones and n.zeros
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
#np.ones and n.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random(3)

array([0.39487541, 0.18896939, 0.02982782])

In [ ]:
#np.random
np.random.random((3,4))

array([[0.82332437, 0.0850619 , 0.73031423, 0.73584682],
       [0.95335188, 0.08852494, 0.55977462, 0.53915484],
       [0.01267205, 0.58040597, 0.54625936, 0.06451697]])

In [ ]:
#np.linspace

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity

np.identity(1)


array([[1.]])

In [ ]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **Array Atributes**

In [ ]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)

In [ ]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
#ndim, give dimnestions
a1.ndim

1

In [ ]:
a2.ndim

2

In [ ]:
#shape
a1.shape

(10,)

In [ ]:
a2.shape

(3, 4)

In [ ]:
a3.shape

(2, 2, 2)

In [ ]:
#size
a3.size

8

In [ ]:
a2.size

12

In [ ]:
#itemsize
a1.itemsize

8

In [ ]:
print(a1.dtype)

int64


### Changing Datatypes


In [ ]:
#astype
a3.dtype

dtype('int64')

In [ ]:
a3.astype(np.int32)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### **Array Operations**

In [ ]:
a1= np.arange(12).reshape(3,4)
a2= np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#scalar operations

#arithmetic
a2+2

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [ ]:
#relatioal
a2>14

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#vector operations
#arithematic

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a1+a2
#adding itemwise


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### **Array Funtions**

In [103]:
a1=np.random.random((3,3))
a1

array([[0.37320951, 0.7755977 , 0.69848849],
       [0.30157342, 0.69500885, 0.11473545],
       [0.07899529, 0.26230373, 0.72313565]])

In [104]:
a2= np.round(a1*100)
np.round(a1*100)
a1

array([[0.37320951, 0.7755977 , 0.69848849],
       [0.30157342, 0.69500885, 0.11473545],
       [0.07899529, 0.26230373, 0.72313565]])

In [105]:
#max/min/sum/prod
np.max(a1)
np.min(a1)
np.prod(a1)

np.float64(7.285425775884463e-05)

In [106]:
# 0--> col and 1--->row
np.max(a1,axis=0)

array([0.37320951, 0.7755977 , 0.72313565])

In [107]:
#mean/median/std/var
np.mean(a1,axis=1)

array([0.61576523, 0.37043924, 0.35481156])

In [109]:
np.median(a1,axis=1)

array([0.69848849, 0.30157342, 0.26230373])

In [110]:
##trigonometru
np.cos(a1)

array([[0.93116194, 0.71400269, 0.76581506],
       [0.95487033, 0.76804803, 0.99342511],
       [0.99688149, 0.96579517, 0.74973443]])

In [111]:
#dot product
a2= np.arange(12).reshape(3,4)
a3= np.arange(12).reshape(4,3)
np.dot(a1,a2)

array([[ 8.69029868, 10.53759438, 12.38489007, 14.23218577],
       [ 3.69791904,  4.80923677,  5.92055449,  7.03187222],
       [ 6.83430014,  7.89873481,  8.96316948, 10.02760415]])

In [112]:
#log and exponnent
np.log(a1)

array([[-0.98561532, -0.25412132, -0.35883659],
       [-1.19874178, -0.3638307 , -2.1651262 ],
       [-2.53836705, -1.33825218, -0.32415845]])

In [113]:
np.exp(a1)

array([[1.4523886 , 2.17188988, 2.01071119],
       [1.35198437, 2.00372681, 1.12157669],
       [1.08219922, 1.2999213 , 2.06088531]])

In [117]:
#rounnd/floor/ceil
np.random.random((2,3))*10

array([[9.5270857 , 9.3281107 , 2.34498381],
       [2.82284646, 3.59997114, 3.85918844]])

In [118]:
np.round(np.random.random((2,3))*10)

array([[1., 8., 3.],
       [6., 4., 8.]])

In [119]:
np.floor(np.random.random((2,3))*10)

array([[9., 3., 2.],
       [7., 0., 1.]])

**indexing and slicing**

In [123]:
a1=np.arange(10)
a2= np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [124]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
a1[-1]

np.int64(9)

In [126]:
a1[0]

np.int64(0)

In [127]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
a2[1,2]

np.int64(6)

In [129]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [131]:
a3[1,0,1]

np.int64(5)

In [132]:
a3[0,1,0]

np.int64(2)

In [134]:
a3[0,0,0]

np.int64(0)

In [135]:
#slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
a1[2:5]

array([2, 3, 4])

In [137]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [138]:
a2[0,:]

array([0, 1, 2, 3])

In [141]:
a2[:,2]

array([ 2,  6, 10])

In [142]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [144]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [146]:
a[1::2,1::3]

array([[[6, 7]]])

In [150]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

### **Iteration**

In [151]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [156]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [157]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [158]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [159]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7


Rshaping

In [166]:
#reshape
a3.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [168]:
#transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [169]:
#ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [170]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

**stacking**

In [172]:

a4= np.arange(12).reshape(3,4)
a5= np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [175]:
#horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [176]:
#verticlal stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**spliting**

In [177]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [179]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [182]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]